# # .pre-commit-config.yaml
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.4.0  # Use the latest stable version
#     hooks:
#       - id: trailing-whitespace  # Remove trailing whitespace
#       - id: end-of-file-fixer  # Ensure files end with a newline
#       - id: check-yaml  # Validate YAML files

#   - repo: https://github.com/psf/black
#     rev: 23.3.0  # Use the latest stable version of Black
#     hooks:
#       - id: black  # Automatically format Python code

#   - repo: https://github.com/pre-commit/mirrors-flake8
#     rev: v5.0.4  # Use the latest stable version of Flake8
#     hooks:
#       - id: flake8  # Lint Python code

#   - repo: https://github.com/pre-commit/mirrors-isort
#     rev: v5.10.1  # Use the latest stable version of isort
#     hooks:
#       - id: isort  # Sort Python imports

#   - repo: https://github.com/pre-commit/mirrors-bandit
#     rev: v1.7.4  # Use the latest stable version of Bandit
#     hooks:
#       - id: bandit  # Security linter for Python

#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.4.0
#     hooks:
#       - id: check-added-large-files  # Prevent large files from being committed
#       - id: check-merge-conflict  # Check for merge conflict markers
# # 