# Generated by Django 5.1.1 on 2024-10-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customtotpdevice_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
